site_name: "Terminale NSI - Lycée Rosa Parks - Saint Denis"
site_url: https://ebrunach.github.io/terminale-nsi/
#nav:
#  - 'accueil' : 'index.md'


theme:
  name: material
  
  custom_dir: my_theme_customizations/
  font: false
  language: fr
  favicon: xtra/favTNSI.png
  icon:
    logo: material/code-greater-than
    repo : fontawesome/brands/github
    admonition:
      note: fontawesome/solid/pen-to-square

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - toc.integrate
    - header.autohide
    - content.code.annotate 
    - content.code.copy

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mode sombre

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Mode clair


markdown_extensions:
  - meta
  - abbr
  - admonition
  - def_list
  - attr_list
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.highlight:
      linenums: None
  - pymdownx.tasklist:
      custom_checkbox: false
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: ⚓︎
      toc_depth: 3
  - sane_lists


plugins:
    - search
    - git-revision-date-localized:
        enable_creation_date: false
        locale: fr
    - awesome-pages:
        collapse_single_pages: false
    - macros
    #- page-to-pdf
    #- mkdocs-jupyter:
    #    include: ["tp.correction.ipynb"]

extra:
  # analytics: 
  #   provider: google
  #   property: G-NXDLLVVQEB

  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:emmanuel.brunache@ac-creteil.fr
      name: Écrire à l'auteur

    - icon: fontawesome/brands/github
      link: https://github.com/ebrunach/terminale-nsi
      name: Dépôt git

    # - icon: fontawesome/solid/school
    #   link: https://lyceemauriac.fr
    #   name: Lycée Angela Davis - Saint Denis

extra_javascript:
  - scripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css


copyright:  CC BY-SA / E.Brunache

repo_url: https://github.com/ebrunach/terminale-nsi

repo_name: ebrunach/terminale-nsi
